---
- name: set up app directory
  become: yes
  ansible.builtin.file:
    path: "{{ path_to_app }}"
    state: directory
    mode: 0775
    owner: "{{ USER }}"
    group: "{{ USER }}"

- name: install gunicorn hello_world
  copy:
    src: hello_world.py
    dest: "{{ path_to_app }}/hello_world.py"

- name: install gunicorn
  pip:
    name: gunicorn
      #virtualenv_python: "{{ item.value.which_python }}"
      #virtualenv_command: "{{ item.value.whereis_virtualenv }}"
    virtualenv: "{{ path_to_app }}/venv"

- name: Create gunicorn logging directories
  become: yes
  file:
    path: "/var/log/gunicorn_{{ app_name }}"
    state: directory
    mode: 0775
    owner: "{{ USER }}"
    group: "{{ USER }}"

- name: Enable logrotate gunicorn apps
  become: yes
  template:
    src: logrotate.j2
    dest: "/etc/logrotate.d/gunicorn_{{ app_name }}"

- name: "create systemd gunicorn {{ app_name }} socket file"
  become: yes
  template:
    src: templates/systemd/gunicorn_socket.j2
    dest: "/usr/lib/systemd/system/gunicorn_{{ app_name }}.socket"
  notify:
    - "restart gunicorn {{ app_name }} service"
    - "restart gunicorn {{ app_name }} socket"

- name: "create systemd gunicorn {{ app_name }} service file"
  become: yes
  template:
    src: templates/systemd/gunicorn_service.j2
    dest: "/usr/lib/systemd/system/gunicorn_{{ app_name }}.service"
  notify:
    - "restart gunicorn service"
    - "restart gunicorn socket"

- name: "gunicorn {{ app_name }} enable & start"
  become: yes
  service:
    name: "{{ item }}"
    enabled: yes
    state: started
  loop:
    - "gunicorn_{{ app_name }}.service"
    - "gunicorn_{{ app_name }}.socket"
  notify:
    - "restart gunicorn service"
    - "restart gunicorn socket"

- name: curl gunicorn socket
  command:
    cmd: "curl -GET --unix-socket /run/gunicorn_{{ app_name }}/{{ app_name }}.sock http://localhost/"
    warn: false
  register: curl_hello_world
  changed_when: False
  when: not ansible_check_mode

- name: debug curl hello_world
  debug:
    var: curl_hello_world.stdout
  changed_when: False
  when: not ansible_check_mode


# vim: ai et ts=2 sw=2 sts=2 nu
