---
- name: set up app directory
  become: yes
  ansible.builtin.file:
    path: "{{ path_to_app_parent }}/{{ website_domain_name }}"
    state: directory
    mode: 0775
    owner: "{{ USER }}"
    group: "{{ USER }}"

- name: install gunicorn hello_world
  copy:
    src: hello_world.py
    dest: "{{ path_to_app_parent }}/{{ website_domain_name }}/hello_world.py"

- name: install gunicorn
  pip:
    name: gunicorn
    virtualenv: "{{ path_to_app_parent }}/{{ website_domain_name }}/venv"

- name: Create gunicorn logging directories
  become: yes
  file:
    path: "/var/log/gunicorn_{{ website_domain_name }}"
    state: directory
    mode: 0775
    owner: "{{ USER }}"
    group: "{{ USER }}"

- name: Enable logrotate gunicorn apps
  become: yes
  template:
    src: logrotate.j2
    dest: "/etc/logrotate.d/gunicorn_{{ website_domain_name }}"

- name: "create systemd gunicorn {{ website_domain_name }} socket file"
  become: yes
  template:
    src: templates/systemd/gunicorn_socket.j2
    dest: "/usr/lib/systemd/system/gunicorn_{{ website_domain_name }}.socket"
  notify:
    - "restart gunicorn service"
    - "restart gunicorn socket"

- name: "create systemd gunicorn {{ website_domain_name }} service file"
  become: yes
  template:
    src: templates/systemd/gunicorn_service.j2
    dest: "/usr/lib/systemd/system/gunicorn_{{ website_domain_name }}.service"
  notify:
    - "restart gunicorn service"
    - "restart gunicorn socket"

- name: "gunicorn {{ website_domain_name }} enable & start"
  become: yes
  service:
    name: "{{ item }}"
    enabled: yes
    state: started
  loop:
    - "gunicorn_{{ website_domain_name }}.service"
    - "gunicorn_{{ website_domain_name }}.socket"
  notify:
    - "restart gunicorn service"
    - "restart gunicorn socket"
  when: not ansible_check_mode

# "curl --unix-socket /run/gunicorn_{{ website_domain_name }}/{{ website_domain_name}}.sock localhost"
- name: curl gunicorn socket
  command:
    cmd: "curl --unix-socket /run/gunicorn_{{ website_domain_name }}/{{ website_domain_name }}.sock http://localhost/"
    warn: false
  register: curl_hello_world
  changed_when: False
  when: not ansible_check_mode

- name: debug curl hello_world
  debug:
    var: curl_hello_world.stdout
  changed_when: False
  when: not ansible_check_mode

- name: remove default nginx enable site
  become: yes
  notify: Restart nginx
  file:
    state: absent
    path: /etc/nginx/sites-enabled/default 

- name: Add nginx config to sites available
  become: yes
  notify: Restart nginx
  template:
    dest: /etc/nginx/sites-available/{{ website_domain_name }}
    src: nginx_conf.j2

- name: Enable nginx config
  become: yes
  notify: Restart nginx
  file:
    state: link
    src: /etc/nginx/sites-available/{{ website_domain_name }}
    dest: /etc/nginx/sites-enabled/{{ website_domain_name }}

- name: curl nginx
  command:
    cmd: "curl -H 'Host: {{ website_domain_name }}' http://0.0.0.0"
    warn: false
  register: curl_nginx
  changed_when: False
  when: not ansible_check_mode

- name: debug curl nginx
  debug:
    var: curl_nginx.stdout
  changed_when: False
  when: not ansible_check_mode

- name: curl nginx https
  command:
    cmd: "curl -k -H 'Host: {{ website_domain_name }}' https://0.0.0.0"
    warn: false
  register: curl_nginx_https
  changed_when: False
  when: not ansible_check_mode

- name: debug curl nginx https
  debug:
    var: curl_nginx_https.stdout
  changed_when: False
  when: not ansible_check_mode

# vim: ai et ts=2 sw=2 sts=2 nu
