---
- name: "Restart gunicorn socket"
  become: yes
  listen: "Restart gunicorn socket"
  service:
    name: "gunicorn_{{ website_domain_name }}.socket"
    state: restarted
    daemon_reload: yes
  when: not ansible_check_mode

- name: "Restart gunicorn service"
  become: yes
  listen: "Restart gunicorn service"
  service:
    name: "gunicorn_{{ website_domain_name }}.service"
    state: restarted
    daemon_reload: yes
  when: not ansible_check_mode

- name: "Restart nginx"
  become: yes
  listen: "Restart nginx"
  service:
    name: "nginx.service"
    state: restarted
    daemon_reload: yes
  when: not ansible_check_mode

# vim: ai et ts=2 sw=2 sts=2 nu
