---
- name: create gunicorn nginx config
  become: yes
  template:
    src: templates/gunicorn.conf.j2
    dest: "/etc/nginx/sites-available/{{ website_domain_name }}.conf"
  notify:
    - restart nginx

- name: "Check if /etc/nginx/sites-available/{{ website_domain_name }}.conf"
  stat:
    path: "/etc/nginx/sites-available/{{ website_domain_name }}.conf"
  register: sites_available 

- name: "Create a symbolic link to sites-enabled for {{ website_domain_name }}"
  become: yes
  ansible.builtin.file:
    src: "/etc/nginx/sites-available/{{ website_domain_name }}.conf"
    dest: "/etc/nginx/sites-enabled/{{ website_domain_name }}.conf"
    state: link
  when: sites_available.stat.exists 
  notify:
    - restart nginx

# vim: ai et ts=2 sw=2 sts=2 nu
