---
- name: Create a new database with name "{{ db_name }}" and specific encoding
  become_user: postgres
  become: yes
  community.postgresql.postgresql_db:
    name: "{{ db_name }}"
    encoding: UTF-8
    lc_collate: en_US.UTF-8
    lc_ctype: en_US.UTF-8
    template: template0
    state: present

- name: Create a new user, "{{ db_user }}"
  become_user: postgres
  become: yes
  community.postgresql.postgresql_user:
    name: "{{ db_user }}"
    password: "{{ db_password }}" 
  register: db_roles

- name: GRANT ALL PRIVILEGES ON DATABASE "{{ db_name }}" TO "{{ db_user }}"
  become_user: postgres
  become: yes
  community.postgresql.postgresql_privs:
    db: "{{ db_name }}"
    privs: ALL
    type: database
    role: "{{ db_user }}"
  when: not ansible_check_mode

- name: Alter user connections parameters
  become_user: postgres
  become: yes
  community.postgresql.postgresql_query:
    query: "{{ item }}"
  loop:
    - "ALTER ROLE {{ db_user }} SET client_encoding TO 'utf8'"
    - "ALTER ROLE {{ db_user }} SET default_transaction_isolation TO 'read committed'"
    - "ALTER ROLE {{ db_user }} SET timezone TO '{{ local_timezone }}'" 
    - "Select * from pg_user"
  register: alter_msg
  when: not ansible_check_mode
  changed_when: False

- name: debug alter user connections
  debug:
    msg: "{{ alter_msg }}"
  changed_when: False
