---
- hosts: nginx_hosts
  vars:
    HOME: "{{ lookup('env', 'HOME') }}"
  vars_files:
    - "{{ HOME }}/configuration/private_vars.yaml"
  connection: local
  roles:
    - role: prep_work
      tags: [prep_work]

# vim: ai et ts=2 sw=2 sts=2 nu
