---
- hosts: nginx_hosts
  vars:
    HOME: "{{ lookup('env', 'HOME') }}"
    USER: "{{ lookup('env', 'USER') }}"
    INSTALL_SYSTEMD_FILES: true
  vars_files:
    #- "{{ HOME }}/configuration/prep_work.yaml"
    #- "{{ HOME }}/configuration/postgres.yaml"
    #- "{{ HOME }}/configuration/gunicorn_setup.yaml"
    #- "{{ HOME }}/configuration/telegram_bot.yaml"
    - "{{ HOME }}/configuration/status.mw.org.yaml"
  connection: local
  roles:
    - role: prep_work
      tags: [prep-work]
    - role: postgres
      tags: [postgres]
    - role: gunicorn_setup
      tags: [gunicorn-setup]
    - role: letsencrypt
      tags: [letsencrypt]
    - role: telegram_bot
      tags: [telegram-bot]

# When creating only a new db for
# for an existing user, use --skip-tags db-user

# vim: ai et ts=2 sw=2 sts=2 nu
